### ISSUE TITLE
fails with newer versions of node?

### ISSUE THREAD

**Issue by tim-peterson** [anatoo/gulper#4]
I upgraded node to v6.2 and when i run `gulper watch` to track my file changes automatically, i get the following error:

```
Saving To...
   - public/fonts

[18:59:01] 'copy' errored after 12 ms
[18:59:01] Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at Object.exports.send (/usr/local/lib/node_modules/gulper/node_modules/node-dev/lib/ipc.js:14:23)
    at /usr/local/lib/node_modules/gulper/node_modules/node-dev/lib/wrap.js:48:7
    at Object.obj.(anonymous function) [as runInThisContext] (/usr/local/lib/node_modules/gulper/node_modules/node-dev/lib/hook.js:58:17)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/gulper/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
TypeError: "listener" argument must be a function
    at _addListener (events.js:216:11)
    at StreamArray.addListener (events.js:270:10)
    at StreamArray.Readable.on (/Users/timrpeterson/laravel/node_modules/stream-array/node_modules/readable-stream/lib/_stream_readable.js:663:33)
    at Function.<anonymous> (/Users/timrpeterson/laravel/node_modules/laravel-elixir/tasks/watch.js:41:24)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/Users/timrpeterson/laravel/node_modules/async-done/index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
events.js:160
      throw er; // Unhandled 'error' event
      ^
```

No idea about this. Thoughts?

**Comment by mujuni88** [comment]
Solution https://github.com/anatoo/gulper/issues/7

**Comment by anatoo** [comment]
Fixed.
