### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by retan** [anatoo/gulper#8]
I cannot run it at all.
Trying a simple `gulper` command and the result is below (replaced some dir names with "...").
```
c:\...\node_modules\.bin\gulp.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Object.obj.(anonymous function) [as runInThisContext] (C:\Users\...\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\hook.js:30:19)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.nodeDevHook [as .js] (C:\Users\...\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\hook.js:61:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[ERROR] 13:14:38 SyntaxError
```

Maybe it has something to do with using gulp version 4.0?

**Comment by stephengardner** [comment]
Yep, bump

**Comment by nagyalex** [comment]
Bump

**Comment by retan** [comment]
Is this package even alive? 
Those were the first replies I got in half a year (I've totally forgotten about it), and no word form the package owner.
@anatoo are you still managing this package?
I would still have a use for this kind of tool.

**Comment by anatoo** [comment]
@retan Do you use gulp 4.0 later? I will try to reproduce this bug.

**Comment by retan** [comment]
@anatoo Exactly. Something above 4.0 combined with babel (to use ES6 syntax - I don't know if that matters). Please notice, I haven't been trying to use your package sins I wrote my original post, so I can't confirm that but now. Though I that @stephengardner  and @nagyalex  have probably encountered the issue as well.

**Comment by nagyalex** [comment]
I use gulp 3.9.1 on Windows node.js if it helps. Can check later node version if needed.

**Comment by anatoo** [comment]
Hmm... I tried to reproduce for a while but it works properly on gulp4.0+ and my environments.
It seems to be an problem on only Windows environments but I don't have Windows machine. 😞

**Comment by DRSDavidSoft** [comment]
I am getting the same issue:

```bash
λ gulp --version
[05:48:17] CLI version 2.0.1
[05:48:17] Local version 4.0.0
```

```
C:\path\to\my\workspace\node_modules\.bin\gulp.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.obj.(anonymous function) [as runInThisContext] (C:\Users\David\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\hook.js:30:19)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.nodeDevHook [as .js] (C:\Users\David\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\hook.js:61:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
[ERROR] 05:47:29 SyntaxError
```
This is because `node-dev` expects a `.js` file, not a `.cmd` wrapper:

```batch
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\gulp\bin\gulp.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\gulp\bin\gulp.js" %*
)
```

**Comment by DRSDavidSoft** [comment]
@anatoo Are you on Linux or macOS?

**Comment by anatoo** [comment]
@DRSDavidSoft Yes.

**Comment by DRSDavidSoft** [comment]
@anatoo That was ambiguous, I meant to ask which one.

**Comment by anatoo** [comment]
Oh, I got it. I developed gulper on macOS.
